// angular/n-shoppingapp/src/app/components/navbar.component.ts
import {Component} from '@angular/core';
import {LoginService} from '../services/login.service';
import {Router,RouterLink} from '@angular/router';
import {CommonModule} from '@angular/common';
@Component({
	selector:"navbar",
	standalone:true,
	imports:[CommonModule],	
	templateUrl:"./navbar.component.html"
})
export class Navbar {
	
	constructor(private login:LoginService, private router:Router) {}

	isUserLogged() {
		return this.login.isUserLogged()
	}
	
	logout() {
		this.login.logout().subscribe({
			next:(data) => console.log(data),
			error:(error) => {
				this.login.setLoginState(false,"");
				this.router.navigate(["/"])
			},
			complete:() => {
				this.login.setLoginState(false,"");
				this.router.navigate(["/"]);
			}
		})
	}
}
<nav class="navbar navbar-extend-lg navbar-light bg-light">
	<p class="navbar-brand">Shopping App</p>
	<ul class="navbar-nav" *ngIf="isUserLogged(); else notLogged">
		<li class="nav-item">
			<a class="nav-link" routerLink="/list">Shopping List</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" routerLink="/form">Add new item</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" routerLink="/" (click)="logout()">Logout</a>
		</li>
	</ul>
	<ng-template #notLogged>
		<ul class="navbar-nav"></ul>
	</ng-template>
</nav>

// react/50_shopping_app/04_stage_statemanager/frontend/src/components/Navbar.tsx
import {Link} from 'react-router';
import useAction from '../hooks/useAction';
import useAppState from '../hooks/useAppState';


const Navbar = () => {
	
	const {isLogged,user} = useAppState();
	const {logout} = useAction();
	
	if(isLogged) {
		return(
			<nav className="navbar navbar-expand-lg navbar-light bg-light">
				<p className="navbar-brand" style={{marginLeft:10}}>Shopping App</p>
				<ul className="navbar-nav">
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/" className="nav-link">Shopping List</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/form" className="nav-link">Add new item</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<p style={{color:"blue"}} className="nav-link">Logged in as {user}</p>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/" onClick={logout} className="nav-link">Logout</Link>
					</li>
				</ul>
			</nav>
		
		)
	} else {
		return(
			<nav className="navbar navbar-expand-lg navbar-light bg-light">
				<p className="navbar-brand" style={{marginLeft:10}}>Shopping App</p>
			</nav>
		)
	}	
}

export default Navbar;
